### PR TITLE
Fix handling of HTML tags in headers

### LINKED ISSUE #16: Doesn't respect existing anchors
I have part of the readme generated by [jsdoc-to-markdown](https://www.npmjs.com/package/jsdoc-to-markdown) and it creates it's own anchors for each function, like this:

```
<a name="Footprint+activate"></a>

#### footprint.activate() ⇒ <code>void</code>
```

Although `toc-md` detects it as a header and adds it to the list,
it refers to different anchors (that don't exist on the page).

```
    - [footprint.activate() ⇒ <code>void</code>](#footprintactivate--codevoidcode)
```

Would nice to recognize existing markers to use them for the reference.

Thank you.

### PR DESCRIPTION
**Pull request by eGavr**
/cc @alexindigo

### CODE REVIEW

**Comment by alexindigo** [comment]
Cool. Thanks. Although it won't solve my problem.
I have pre-existing anchor, that I'd like to reuse for table of contents.

Basically when you have `<a name="">` tag just before `<h*>` tag then you can copy it's target instead of generating new one for the text.
What do you think?

Thanks.

**Comment by eGavr** [comment]
Can you give a real example of an `md`-file and a TOC for it which you want to be generated by this tool ? :)

**Comment by alexindigo** [comment]
Sure.

```md
# footprint

Generic Footprint API client

| compression         |     size |
| :------------------ | -------: |
| footprint.js        | 38.86 kB |
| footprint.min.js    | 12.29 kB |
| footprint.min.js.gz |   3.5 kB |


## Table of Contents

<!-- TOC -->
- [Install](#install)
- [Example](#example)
  - [Extending `Footprint`](#extending-footprint)
  - [Instantiating extended object](#instantiating-extended-object)
- [API Reference](#api-reference)
  - [Footprint](#footprint)
    - [footprint.getActions ⇒ <code>array</code>](#footprintgetactions--codearraycode)
    - [footprint.transport ⇒ <code>void</code>](#footprinttransport--codevoidcode)
    - [footprint.activate() ⇒ <code>void</code>](#footprintactivate--codevoidcode)
    - [footprint.createEvent() ⇒ <code>void</code>](#footprintcreateevent--codevoidcode)
    - [footprint.getEventData(data) ⇒ <code>object</code>](#footprintgeteventdatadata--codeobjectcode)
    - [footprint.getOptions(options) ⇒ <code>object</code>](#footprintgetoptionsoptions--codeobjectcode)
    - [footprint.log(...message) ⇒ <code>void</code>](#footprintlogmessage--codevoidcode)
      - [log.debug(...message) ⇒ <code>void</code>](#logdebugmessage--codevoidcode)
      - [log.error(...message) ⇒ <code>void</code>](#logerrormessage--codevoidcode)
      - [log.info(...message) ⇒ <code>void</code>](#loginfomessage--codevoidcode)
      - [log.notice(...message) ⇒ <code>void</code>](#lognoticemessage--codevoidcode)
      - [log.warning(...message) ⇒ <code>void</code>](#logwarningmessage--codevoidcode)
    - [footprint.send([endpoint], data, callback) ⇒ <code>mixed</code>](#footprintsendendpoint-data-callback--codemixedcode)
    - [footprint.stringify(data) ⇒ <code>string</code>](#footprintstringifydata--codestringcode)
- [Coverage](#coverage)

<!-- TOC END -->

## Install

`npm install --save footprint`

## Example

### Extending `Footprint`

Here goes js example

### Instantiating extended object

Another js example

## API Reference

<a name="Footprint"></a>

### Footprint

Creates Footprint API client instance

Base "class" for service specific implementations
holds reference and generic methods

**Kind**: global interface  
**Params**

-   options <code>object</code> - list of options


-   [Footprint](#Footprint)
    -   _interface_
        -   [.getActions](#Footprint+getActions) ⇒ <code>array</code>
        -   [.transport](#Footprint+transport) ⇒ <code>void</code>
    -   _function_
        -   [.activate()](#Footprint+activate) ⇒ <code>void</code>
        -   [.createEvent()](#Footprint+createEvent) ⇒ <code>void</code>
        -   [.getEventData(data)](#Footprint+getEventData) ⇒ <code>object</code>
        -   [.getOptions(options)](#Footprint+getOptions) ⇒ <code>object</code>
        -   [.log(...message)](#Footprint+log) ⇒ <code>void</code>
            -   [.debug(...message)](#Footprint+log.debug) ⇒ <code>void</code>
            -   [.error(...message)](#Footprint+log.error) ⇒ <code>void</code>
            -   [.info(...message)](#Footprint+log.info) ⇒ <code>void</code>
            -   [.notice(...message)](#Footprint+log.notice) ⇒ <code>void</code>
            -   [.warning(...message)](#Footprint+log.warning) ⇒ <code>void</code>
        -   [.send([endpoint], data, callback)](#Footprint+send) ⇒ <code>mixed</code>
        -   [.stringify(data)](#Footprint+stringify) ⇒ <code>string</code>

-

<a name="Footprint+getActions"></a>

#### footprint.getActions ⇒ <code>array</code>

[Reference method] Provides list of report actions

-   needs to be implemented

**Kind**: instance interface of <code>[Footprint](#Footprint)</code>  
**Returns**: <code>array</code> - list of action to register  

-

<a name="Footprint+transport"></a>

#### footprint.transport ⇒ <code>void</code>

[Reference method] Sends provided data "over the wire"

-   needs to be implemented

**Kind**: instance interface of <code>[Footprint](#Footprint)</code>  
**Params**

-   url <code>string</code> - endpoint url
-   data <code>object</code> - data to send
-   options <code>object</code> - options to modify transport behavior
-   callback <code>function</code> - invoked after transaction has finished

-

<a name="Footprint+activate"></a>

#### footprint.activate() ⇒ <code>void</code>

Activates footprint reporting by registering available actions

**Kind**: instance method of <code>[Footprint](#Footprint)</code>  

-

<a name="Footprint+createEvent"></a>

#### footprint.createEvent() ⇒ <code>void</code>

Creates new event object with required properties

**Kind**: instance method of <code>[Footprint](#Footprint)</code>  

-

<a name="Footprint+getEventData"></a>

#### footprint.getEventData(data) ⇒ <code>object</code>

Combines event specific data with common values of the newly created event

**Kind**: instance method of <code>[Footprint](#Footprint)</code>  
**Returns**: <code>object</code> - combined event data  
**Params**

-   data <code>object</code> - event specific values

-

<a name="Footprint+getOptions"></a>

#### footprint.getOptions(options) ⇒ <code>object</code>

Produces combined defaults and options object (shallow copy)
merged with parent options and defaults, recursively

**Kind**: instance method of <code>[Footprint](#Footprint)</code>  
**Returns**: <code>object</code> - combined object of default and custom options  
**Params**

-   options <code>object</code> - initialization options

-

<a name="Footprint+log"></a>

#### footprint.log(...message) ⇒ <code>void</code>

Logs supplied messages, used as main/generic gateway
to the logger and as shortcut for `log.notice`

**Kind**: instance method of <code>[Footprint](#Footprint)</code>  
**Params**

-   ...message <code>mixed</code> - message to log


-   [.log(...message)](#Footprint+log) ⇒ <code>void</code>
    -   [.debug(...message)](#Footprint+log.debug) ⇒ <code>void</code>
    -   [.error(...message)](#Footprint+log.error) ⇒ <code>void</code>
    -   [.info(...message)](#Footprint+log.info) ⇒ <code>void</code>
    -   [.notice(...message)](#Footprint+log.notice) ⇒ <code>void</code>
    -   [.warning(...message)](#Footprint+log.warning) ⇒ <code>void</code>

-

<a name="Footprint+log.debug"></a>

##### log.debug(...message) ⇒ <code>void</code>

Logs `debug` level messages

**Kind**: static method of <code>[log](#Footprint+log)</code>  
**Params**

-   ...message <code>mixed</code> - message to log

-

<a name="Footprint+log.error"></a>

##### log.error(...message) ⇒ <code>void</code>

Logs `error` level messages

**Kind**: static method of <code>[log](#Footprint+log)</code>  
**Params**

-   ...message <code>mixed</code> - message to log

-

<a name="Footprint+log.info"></a>

##### log.info(...message) ⇒ <code>void</code>

Logs `info` level messages

**Kind**: static method of <code>[log](#Footprint+log)</code>  
**Params**

-   ...message <code>mixed</code> - message to log

-

<a name="Footprint+log.notice"></a>

##### log.notice(...message) ⇒ <code>void</code>

Logs `notice` level messages

**Kind**: static method of <code>[log](#Footprint+log)</code>  
**Params**

-   ...message <code>mixed</code> - message to log

-

<a name="Footprint+log.warning"></a>

##### log.warning(...message) ⇒ <code>void</code>

Logs `warning` level messages

**Kind**: static method of <code>[log](#Footprint+log)</code>  
**Params**

-   ...message <code>mixed</code> - message to log

-

<a name="Footprint+send"></a>

#### footprint.send([endpoint], data, callback) ⇒ <code>mixed</code>

Augments and sends data to the provided endpoint (relative to the baseUrl)

**Kind**: instance method of <code>[Footprint](#Footprint)</code>  
**Returns**: <code>mixed</code> - - passes back `this.transport` invocation result  
**Params**

-   [endpoint] <code>string</code> - endpoint handle
-   data <code>object</code> - data to send
-   callback <code>function</code> - invoked after transaction has finished

-

<a name="Footprint+stringify"></a>

#### footprint.stringify(data) ⇒ <code>string</code>

Stringifies provided data to send over the "wire"

**Kind**: instance method of <code>[Footprint](#Footprint)</code>  
**Returns**: <code>string</code> - json string  
**Params**

-   data <code>object</code> - object to stringify

-

## Coverage

Here goes coverage info

```

Thank you.

**Comment by eGavr** [comment]
Still I can not understand the problem or a feature request :) 

You want the tool to display in a TOC the text which is situated in the attribute `name` of tag `a` instead of a real text in heads?

**Comment by alexindigo** [comment]
Let's focus on one of the headers that ends up in the TOC, for example this one:

```
<a name="Footprint+transport"></a>

#### footprint.transport ⇒ <code>void</code>
```

after I run `toc-md` I get following reference to this header at the top of my file:

```
- [footprint.transport ⇒ <code>void</code>](#footprinttransport--codevoidcode)
```

As you can see it references `#footprinttransport--codevoidcode` anchor, assuming that Github and NPM would generate it while rendering markdown into HTML.

But there is another anchor already present on the page for this header – `name="Footprint+transport"`,
so it would be nice if `toc-md` could recognize it and use it instead of auto-generated one.

So TOC would look like following:

```
- [footprint.transport ⇒ <code>void</code>](#Footprint+transport)
```

PS. Also, this is internal project and we're using Stash, not Github, so `md->html` rendering is a bit different.

I hope it helped. 

Thank you.

**Comment by eGavr** [comment]
Ohhh! Now I've understood :)

I think that it could be implemented :)

I'll merge this PR, it does not close your issue, but fixes another bug :)

**Comment by alexindigo** [comment]
Thanks a lot.

**Pull request merged**
