### PR TITLE
Bumped marked version #14

### PR DESCRIPTION
**Pull request by alexindigo**
Re: https://nodesecurity.io/advisories/marked_redos

### CODE REVIEW

**Comment by eGavr** [comment]
Tests failed :(

**Comment by alexindigo** [comment]
Looks like it's that regex security fix in play, and update requires code changes.
Then I'm out of my waters here.

**Comment by eGavr** [comment]
I looked more precise at failing test and understood that I can not update `marked` to `0.3.4` or later, because this update will break correct test, more details can be found in an [issue](https://github.com/chjj/marked/issues/729).

**Comment by alexindigo** [comment]
Cool. Thanks.

**Pull request closed without merging**
